//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapWebServiceClient.ProductServices
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://productservice.example.com/2025", ConfigurationName="SoapWebServiceClient.ProductServices.ProductServicePort")]
    public interface ProductServicePort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://productservice.example.com/2025/GetProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapWebServiceClient.ProductServices.GetProductResponse> GetProductAsync(SoapWebServiceClient.ProductServices.GetProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://productservice.example.com/2025/GetAllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<SoapWebServiceClient.ProductServices.GetAllProductsResponse> GetAllProductsAsync(SoapWebServiceClient.ProductServices.GetAllProductsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProduct", Namespace="http://productservice.example.com/2025", Order=0)]
        public SoapWebServiceClient.ProductServices.GetProductRequestBody Body;
        
        public GetProductRequest()
        {
        }
        
        public GetProductRequest(SoapWebServiceClient.ProductServices.GetProductRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetProductRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int productId;
        
        public GetProductRequestBody()
        {
        }
        
        public GetProductRequestBody(int productId)
        {
            this.productId = productId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProductResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProductResponse", Namespace="http://productservice.example.com/2025", Order=0)]
        public SoapWebServiceClient.ProductServices.GetProductResponseBody Body;
        
        public GetProductResponse()
        {
        }
        
        public GetProductResponse(SoapWebServiceClient.ProductServices.GetProductResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetProductResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Success;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ProductId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Message;
        
        public GetProductResponseBody()
        {
        }
        
        public GetProductResponseBody(bool Success, int ProductId, string Nombre, string Message)
        {
            this.Success = Success;
            this.ProductId = ProductId;
            this.Nombre = Nombre;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProducts", Namespace="http://productservice.example.com/2025", Order=0)]
        public SoapWebServiceClient.ProductServices.GetAllProductsRequestBody Body;
        
        public GetAllProductsRequest()
        {
        }
        
        public GetAllProductsRequest(SoapWebServiceClient.ProductServices.GetAllProductsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllProductsRequestBody
    {
        
        public GetAllProductsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllProductsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllProductsResponse", Namespace="http://productservice.example.com/2025", Order=0)]
        public SoapWebServiceClient.ProductServices.GetAllProductsResponseBody Body;
        
        public GetAllProductsResponse()
        {
        }
        
        public GetAllProductsResponse(SoapWebServiceClient.ProductServices.GetAllProductsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetAllProductsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool Success;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Total;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message;
        
        public GetAllProductsResponseBody()
        {
        }
        
        public GetAllProductsResponseBody(bool Success, int Total, string Message)
        {
            this.Success = Success;
            this.Total = Total;
            this.Message = Message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ProductServicePortChannel : SoapWebServiceClient.ProductServices.ProductServicePort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ProductServicePortClient : System.ServiceModel.ClientBase<SoapWebServiceClient.ProductServices.ProductServicePort>, SoapWebServiceClient.ProductServices.ProductServicePort
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ProductServicePortClient() : 
                base(ProductServicePortClient.GetDefaultBinding(), ProductServicePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.ProductServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductServicePortClient(EndpointConfiguration endpointConfiguration) : 
                base(ProductServicePortClient.GetBindingForEndpoint(endpointConfiguration), ProductServicePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductServicePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ProductServicePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductServicePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ProductServicePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ProductServicePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapWebServiceClient.ProductServices.GetProductResponse> SoapWebServiceClient.ProductServices.ProductServicePort.GetProductAsync(SoapWebServiceClient.ProductServices.GetProductRequest request)
        {
            return base.Channel.GetProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapWebServiceClient.ProductServices.GetProductResponse> GetProductAsync(int productId)
        {
            SoapWebServiceClient.ProductServices.GetProductRequest inValue = new SoapWebServiceClient.ProductServices.GetProductRequest();
            inValue.Body = new SoapWebServiceClient.ProductServices.GetProductRequestBody();
            inValue.Body.productId = productId;
            return ((SoapWebServiceClient.ProductServices.ProductServicePort)(this)).GetProductAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoapWebServiceClient.ProductServices.GetAllProductsResponse> SoapWebServiceClient.ProductServices.ProductServicePort.GetAllProductsAsync(SoapWebServiceClient.ProductServices.GetAllProductsRequest request)
        {
            return base.Channel.GetAllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoapWebServiceClient.ProductServices.GetAllProductsResponse> GetAllProductsAsync()
        {
            SoapWebServiceClient.ProductServices.GetAllProductsRequest inValue = new SoapWebServiceClient.ProductServices.GetAllProductsRequest();
            inValue.Body = new SoapWebServiceClient.ProductServices.GetAllProductsRequestBody();
            return ((SoapWebServiceClient.ProductServices.ProductServicePort)(this)).GetAllProductsAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ProductServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7141/ProductService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ProductServicePortClient.GetBindingForEndpoint(EndpointConfiguration.ProductServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ProductServicePortClient.GetEndpointAddress(EndpointConfiguration.ProductServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            ProductServicePort,
        }
    }
}
